final: out/main.o out/menu.o out/inventory_system.o
	gcc out/main.o out/menu.o out/inventory_system.o -o final

out/main.o: src/main.c src/menu.h src/inventory_system.h
	gcc -c src/main.c -o out/main.o

out/menu.o: src/menu.c
	gcc -c src/menu.c -o out/menu.o

out/inventory_system.o: src/inventory_system.c
	gcc -c src/inventory_system.c -o out/inventory_system.o
