final: out/main.o out/menu.o out/invetory_system.o
	gcc out/main.o out/menu.o out/invetory_system.o -o final

out/main.o: src/main.c
	gcc -c src/main.c -o out/main.o

out/menu.o: src/menu.c
	gcc -c src/menu.c -o out/menu.o

out/invetory_system.o: src/invetory_system.c
	gcc -c src/invetory_system.c -o out/invetory_system.o
